### ISSUE TITLE
code is not complete！

### ISSUE THREAD

**Issue by xiaofeifei-1** [matval/wayfaster#1]

**Comment by clement-chupin** [comment]
(Please note: The code in this repository is currently undergoing updates and is not yet complete. Stay tuned for the latest versions!)

**Comment by xiaofeifei-1** [comment]
> (Please note: The code in this repository is currently undergoing updates and is not yet complete. Stay tuned for the latest versions!)

Thank you, sir! Look forward to your full version of the code. I wish you a good paper!

**Comment by Bunmsel** [comment]
@clement-chupin I was reading your paper and trying to implement the code but I notice from the custom packages in train.py error was raise for not seeing the folder dataloader, train_configs and trainer.

**Comment by matval** [comment]
Hi @Bunmsel,

Thank you for your interest in our work. The error you encountered is due to a few missing files. I plan to release the complete code this week, so please stay tuned.

**Comment by doctorcolossus** [comment]
> Hi @Bunmsel,
> 
> Thank you for your interest in our work. The error you encountered is due to a few missing files. I plan to release the complete code this week, so please stay tuned.

Looking forward to this! 🙂

FYI, `README.md` currently references `requirements.txt`, which does not yet appear to exist, but I assume this will be fixed along with the other missing stuff this week.
