### ISSUE TITLE
About dataset generation

### ISSUE THREAD

**Issue by Seongwoo-Moon** [matval/wayfaster#2]
Your research was very interesting. I would like to know how you generate the dataset and how to estimate mu and nu using MHE, if possible. Thank you!

**Comment by matval** [comment]
Hi @Seongwoo-Moon, I'm glad you found our research interesting!

We estimate the traversability coefficients $\mu$ and $\nu$ using the CasADi library for optimization. In our implementation, we use the MHE approach to optimize the cost function described in our paper [here](https://arxiv.org/abs/2203.12071). During this process, $\mu$ and $\nu$ are held constant over a short horizon.

For our experiments, we set the horizon length $N$ to 8 and the time step to 0.5 seconds. The MHE algorithm fuses GPS measurements and control commands to estimate the traversability parameters and state values effectively.

If you have any more questions or need further details, feel free to ask!

**Comment by Seongwoo-Moon** [comment]
Thank you for your detail explanation!!! I am looking forward to your upcoming research
